x-env: &env
  POSTGRES_URL: database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  cards:
    build:
      context: .
    environment: *env
    ports:
      - 8000:80
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16.0
    environment: *env
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

